development:
  adapter: any_cable

test:
  adapter: any_cable

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: anycable_rails_demo_production
